API specifications as per OpenAPI3.0 standard
DataDeliInc/LambdaStaticAssets pull request #3
Opened 2022-03-06 07:17 UTC by muralidatadeli

2022-03-06 12:57 UTC, upendra-datadeli commented
Please resolve the conflicts

2022-03-06 12:57 UTC, upendra-datadeli requested changes

2022-03-06 12:57 UTC, upendra-datadeli commented on resources/aoiViewerApiOA3.yml
> +  - url: https://api.test.datadeli.com/static/aoiViewerApi.yml
I don't think url should be this.

2022-03-06 12:57 UTC, upendra-datadeli commented on resources/aoiViewerApiOA3.yml
> +  title: Geospatial Application
We need to come up with a better name

2022-03-06 15:06 UTC, muralidatadeli commented on resources/aoiViewerApiOA3.yml
> +  - url: https://api.test.datadeli.com/static/aoiViewerApi.yml
corrected as per https://swagger.io/docs/specification/api-host-and-base-path/

2022-03-06 15:08 UTC, muralidatadeli commented on resources/aoiViewerApiOA3.yml
> +  title: Geospatial Application
Ok. Please suggest

2022-03-07 03:50 UTC, upendra-datadeli commented
Can you please make sure it works with AppUI before merging? Thanks!

2022-03-07 03:51 UTC, upendra-datadeli approved these changes

2022-03-07 07:04 UTC, merged